---

- name: install jupyterhub config file
  template: src=jupyterhub_config.py.j2 dest={{ jupyterhub.config_dir }}/{{ jupyterhub.config_file }} owner=root group=root mode=0644
  become: true
  notify: restart jupyterhub
  tags:
  - configuration

- name: create cookie secret
  shell: openssl rand -hex 32 > "{{ jupyterhub.srv_dir }}/cookie_secret"
  args:
    creates: "{{ jupyterhub.srv_dir }}/cookie_secret"
  notify: restart jupyterhub
  become: true
  tags: 
  - configuration

- name: set cookie secret file attributes
  file:
    path: "{{ jupyterhub.srv_dir }}/cookie_secret"
    owner: "{{ jupyterhub.user }}"
    group: "{{ jupyterhub.group }}"
    mode: 0600
  tags:
  - configuration