---
- name: create conda environment
  shell: "{{ conda.prefix }}/bin/conda create --quiet --yes --name {{ jupyterhub.environment.name }} python={{ jupyterhub.environment.python_version }} python"
  args:
    creates: "{{ conda.prefix }}/envs/{{ jupyterhub.environment.name }}"
    executable: /bin/bash
  notify: restart jupyterhub
  tags:
    - packages

- name: install jupyterhub dependencies via conda
  conda: name={{ item }} state=present extra_args="--name {{ jupyterhub.environment.name }}" executable="{{ conda.prefix }}/bin/conda"
  become: true
  with_items: "{{ jupyterhub.environment.conda_packages }}"
  notify: restart jupyterhub
  tags:
    - packages

- name: install jupyterhub dependencies via pip
  pip: name={{ item }} state=present editable=false executable={{ conda.prefix }}/envs/{{ jupyterhub.environment.name }}/bin/pip
  become: true
  with_items: "{{ jupyterhub.environment.pip_packages }}"
  notify: restart jupyterhub
  tags:
    - packages