---

- name: install single user page.html file for Google Analytics
  template: src=page.html.j2 dest={{ jupyter.templates_dir }}/page.html owner=root group=root mode=0644
  become: true
  when: jupyter.ga_tracking_id is defined and jupyter.ga_tracking_id != ''

